language: python
python:
- '3.5'
- '3.6'
- 3.7-dev
sudo: required
dist: xenial
cache:
- pip
- apt
install:
- python setup.py install
script:
- pip install .[test]
- python setup.py test
- pip install .[doc]
- cd doc; make html
- cd ..
deploy:
  provider: pypi
  user: dburkhardt
  password: ${PYPI_PASSWORD}
  distributions: sdist bdist_wheel
  skip_existing: true
  skip_cleanup: true
  on:
    tags: true
    branch: master
after_success:
- coveralls
