language: python
warnings_are_errors: false
python:
  - '3.5'
  - '3.6'
  - '3.7'
  - '3.8'
dist: xenial
cache:
- pip
- apt
install:
- pip install -r requirements.txt
- pip install .
script:
- python -c "import meld"
- pip install .[test]
- python setup.py test
- pip install -r doc/source/requirements.txt
- cd doc; make html
- cd ..
deploy:
  provider: pypi
  user: dburkhardt
  password: ${PYPI_PASSWORD}
  distributions: sdist bdist_wheel
  skip_existing: true
  skip_cleanup: true
  on:
    tags: true
    branch: master
after_success:
- coveralls
